# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'device-where' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for device-where
  pod 'Firebase/Core'

  target 'device-whereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'device-whereUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
